import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "normalize.css/normalize.css";
import { UserContextProvider } from "./contexts/UserContext";
const inter = Inter({ subsets: ["latin"] });
import "./globalStyling.scss";
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<UserContextProvider>{children}</UserContextProvider>
			</body>
		</html>
	);
}
