import type { Metadata } from "next";
import "normalize.css/normalize.css";
import "./globalStyling.scss";
import Providers from "./components/Providers/Providers";
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
